#!/bin/bash
# 03-18-2010 Dave Crouse
# Example code on how to read a spreadsheet IE: spreadsheet exported to CSV file
# This script reads in a csv file and does stuff with the data line by line.

# input = /path/to/data/file
input=$1
[ $# -eq 0 ] && { echo "Usage: $0 arg1"; exit 1; }

while read -r line
do
        # I tend to use the | pipe delimeter when exporting my spreadsheets to text files.
        # Change the IFS below if you are NOT using the pipe delimeter.
        IFS="|" read -r f1 f2 f3 f4 f5 <<<"$line"

        # Data is now in the variables, do stuff here :)
        echo $f1 $f2 $f3 $f4 $f5

done <"$input"

